alias python="env/bin/python2.7"
alias whichpython="which env/bin/python2.7"
alias ipy="python -c 'import IPython;IPython.terminal.ipapp.launch_new_instance()' notebook"
alias pip="env/bin/pip"
alias whichpip="which env/bin/pip"
